name: tek
description: A new Flutter project.

dependencies:
  path_provider: ^0.2.1+1
  yaml: 2.1.12
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
    - assets/Akuma.yaml
    - assets/Alisa.yaml
    - assets/Asuka.yaml
    - assets/Bob.yaml
    - assets/Bryan.yaml
    - assets/Claudio.yaml
    - assets/Devil Jin.yaml
    - assets/Dragunov.yaml
    - assets/Eddy.yaml
    - assets/Eliza.yaml
    - assets/Feng.yaml
    - assets/Gigas.yaml
    - assets/Heihachi.yaml
    - assets/Hwoarang.yaml
    - assets/Jack-7.yaml
    - assets/Jin.yaml
    - assets/Josie.yaml
    - assets/Katarina.yaml
    - assets/Kazumi.yaml
    - assets/Kazuya.yaml
    - assets/King.yaml
    - assets/Kuma.yaml
    - assets/Lars.yaml
    - assets/Law.yaml
    - assets/Lee.yaml
    - assets/Leo.yaml
    - assets/Lili.yaml
    - assets/Lucky Chloe.yaml
    - assets/Master Raven.yaml
    - assets/Miguel.yaml
    - assets/Nina.yaml
    - assets/Paul.yaml
    - assets/Shaheen.yaml
    - assets/Steve.yaml
    - assets/Xiaoyu.yaml
    - assets/Yoshimitsu.yaml


  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
